- pom.xml
- src/main/java/com/kube/noon/places/domain/Place.java
- src/main/java/com/kube/noon/places/exception/PlaceNotFoundException.java
- src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepository.java
- src/main/java/com/kube/noon/places/repository/PlacesRepository.java
- src/test/java/com/kube/noon/places/repository/TestPlacesNaverMapsApiRepository.java
PlacesRepository는 구조적으로 외부 API에서 데이터를 가져옵니다.
Naver Maps API에서 데이터 가져오는 것을 Repository로 추상화해서 구현했습니다.
#10
[네이버 지도 API 가이드를 참고하세요](https://www.ncloud.com/product/applicationService/maps)
> feat: 네이버 지도 기반 Geocoding, Reverse Geocoding API 데이터 가져오기 구현

- src/main/java/com/kube/noon/common/PublicRange.java
- src/main/resources/application.properties
- src/main/resources/mybatis-mapper/SampleMapper.xml
- src/test/java/com/kube/noon/common/TestPublicRange.java
MyBatis 관련 설정, 여러 곳에서 사용되는 PublicRange 정의했음
- application.properties 파일에 mapper 파일 위치 정의
- mybatis mapper 파일 경로 생성
- 공개범위를 나타내는 PublicRange enum 정의
Issue: #17 
추가로 Test 클래스로 enum을 사용하는 방법 두어 가지 예시 코드로 작성했습니다. 참고 바랍니다.
> chore: 공통으로 쓰이는 객체하고 환경설정 정의

- src/main/resources/application.properties
application.properties에 JPA와 관련된 필요한 설정을 추가함
- JPA에서 생성해 주는 SQL 출력
- DDL 방지
Issue: #20
> chore: JPA 관련 설정 추가

- .gitignore
- pom.xml
- src/main/java/com/kube/noon/member/domain/Member.java
- src/main/java/com/kube/noon/member/dto/MemberRelationshipSearchCriteriaDto.java
- src/main/java/com/kube/noon/member/dto/MemberSearchCriteriaDto.java
- src/main/java/com/kube/noon/member/dto/UpdateMemberDto.java
- src/main/java/com/kube/noon/member/repository/MemberJpaRepository.java
- src/main/java/com/kube/noon/member/repository/MemberJpaRepositoryQuery.java
- src/main/java/com/kube/noon/member/repository/MemberJpaRepositoryQueryImpl.java
- src/main/java/com/kube/noon/member/repository/MemberRepository.java
- src/main/java/com/kube/noon/member/repository/MemberRepositoryImpl.java
- src/main/java/com/kube/noon/member/service/MemberService.java
- src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
- src/test/java/com/kube/noon/member/repository/TestMemberRepository.java
- src/test/java/com/kube/noon/member/service/TestMemberService.java
Related To : #29
Dto 리팩토링,UpdateMemberDto 리팩토링
Dto를 좀 더 사용하기 쉽게 만들었습니다.
> Refactor:Dto 리팩토링,UpdateMemberDto 리팩토링

- src/main/java/com/kube/noon/common/messagesender/MessageSender.java
- src/main/java/com/kube/noon/common/messagesender/NotificationCoolSmsMessageSender.java
- src/main/java/com/kube/noon/common/messagesender/NotificationEmptyMessageSender.java
- src/main/java/com/kube/noon/common/messagesender/NotificationMessageSender.java
- src/main/java/com/kube/noon/config/BeanConfig.java
- src/main/java/com/kube/noon/notification/service/NotificationServiceImpl.java
- src/main/java/com/kube/noon/places/controller/PlacesRestController.java
- src/main/java/com/kube/noon/setting/controller/SettingRestController.java
- src/main/java/com/kube/noon/setting/domain/Setting.java
- src/main/java/com/kube/noon/setting/dto/SettingDto.java
- src/main/java/com/kube/noon/setting/service/SettingService.java
- src/main/java/com/kube/noon/setting/service/SettingServiceImpl.java
- src/test/java/com/kube/noon/setting/service/TestSettingServiceImpl.java
SettingRestController와 PlacesRestController를 구현했다.
- SettingRestController 구현
- PlacesRestController 구현
- NotificationTransmissionAgent 리팩토링
Issue: #54, #41
> feat: SettingRestController, PlacesRestController 구현

- src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepository.java
- src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepositoryImpl.java
- src/main/java/com/kube/noon/customersupport/repository/NoticeRepository.java
- src/main/java/com/kube/noon/customersupport/service/CustomerSupportService.java
- src/main/java/com/kube/noon/customersupport/service/CustomerSupportServiceImpl.java
- src/main/resources/mybatis-mapper/buildingProfile/BuildingProfileMapper.xml
- src/test/java/com/kube/noon/customersupport/repository/TestCustomerSupportRepository.java
- src/test/java/com/kube/noon/customersupport/service/TestCustomerSupportService.java
리스트를 가져오는 모든 서비스에 페이징을 추가했습니다.
또한, Repository Test까지 마쳤던 것들은 모두 Service작성을 완료하여 Service Test까지 마쳤습니다.
기존 메서드도 활용할 수 있도록 그대로 두고, 
pageable객체를 파라미터로 받는 메서드를 오버로딩하는 방식으로 추가했습니다.
JPARepository를 쓰지 않은, 직접 작성한 Impl구현체에는 Pageable 및 PageImpl로 페이징 로직을 구현했습니다.
[springframework.data.domain](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/package-summary.html)
> feat : 페이징 적용 및 Service Test

- .gitignore
- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/service/FeedService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/java/com/kube/noon/feed/service/recommend/FeedRecommendationMemberId.java
getFeedListByBuilding 메서드 변경으로 에러가 나서 해결하였습니다.
`BuildingProfileRestController` 에 다음 메서드에 에러가 났습니다.
```
/**
* 건물의 피드 목록 가져오기
*/
@GetMapping("/getBuildingFeedList")
public List<FeedSummaryDto> getBuildingFeedList(@RequestParam("buildingId") int buildingId) {
return feedService.getFeedListByBuilding(buildingId);
}
```
이는 제가 어제 `getFeedListByBuilding(int buildingId)`를 `getFeedListByBuilding(String memberId, int buildingId)` 로 변경해서 생긴 현상으로, 다음과 같이 메서드를 오버로딩하여 임시로 해결했습니다.
(FeedServiceImpl.java)
```
@Override
public List<FeedSummaryDto> getFeedListByBuilding(String memberId, int buildingId) {
Member member = Member.builder().memberId(memberId).build();
Building building = Building.builder().buildingId(buildingId).build();
List<Feed> entities = new ArrayList<>(); …
```
> hotfix : getFeedListByBuilding Error 해결

- src/main/java/com/kube/noon/config/WebConfig.java
- src/main/java/com/kube/noon/member/controller/ApiResponse.java
- src/main/java/com/kube/noon/member/controller/ApiResponseFactory.java
- src/main/java/com/kube/noon/member/controller/MemberRestController.java
- src/main/java/com/kube/noon/member/controller/RequestContext.java
- src/main/java/com/kube/noon/member/service/LoginAttemptCheckerAgent.java
- src/main/java/com/kube/noon/member/service/MemberTransactionalService.java
- src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
Related To:#83
메인에 에러나서 바로 풀리퀘스트 올립니다.
실수로 메인에 에러나는 것 머지되어버려서 바로 풀리퀘스트 올립니다.
> HotFix:메인에 지금 에러나서 고쳐진거 바로 푸시하기 위해 커밋

- src/main/java/com/kube/noon/customersupport/controller/CustomerSupportRestController.java
> HOTFIX : 피드delete관련 hotfix

- src/main/java/com/kube/noon/chat/controller/ChatroomRestController.java
- src/main/java/com/kube/noon/chat/repository/ChatroomRepository.java
- src/main/java/com/kube/noon/chat/service/ChatroomSearchService.java
- src/main/java/com/kube/noon/chat/service/ChatroomService.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomSearchServiceImpl.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomServiceImpl.java
- src/main/resources/application-prod.properties
- src/test/java/com/kube/noon/chat/ChatroomSearchServiceImplTest.java
채팅방 조회 기능을 추가했습니다
- 건물별 채팅방 조회, 검색 및 전체 채팅방 검색
> Z ral dog/#38/chatroom search service

- .gitignore
- Dockerfile
- pom.xml
- src/main/resources/application.properties
Dockerfile을 정의하고 빌드를 위한 세팅을 했습니다.
- Dockerfile 작성
- .gitignore에 application-prod.properties 추가
- application.properties 수정
- Dependency 충돌 제거
Issue: #105
> chore: 빌드 세팅

- src/main/java/com/kube/noon/config/WebConfig.java
- src/main/resources/application.properties
application.properties에 개발용 CORS 설정
- Allowed Origins: http://localhost:3000, http://127.0.0.1:3000
- Allowed Methods: GET, POST
- Allowed Headers: Cookie, Content-Type, Content-Length, Host, Accept, Accept-Encoding
- Allow Credentials: true
Issue: #109
> chore: CORS 설정

- src/main/java/com/kube/noon/common/HealthCheckRestController.java
- src/main/java/com/kube/noon/common/security/AccessDefinition.java
HealthCheck용 RestController 추가
-
> feat : HealthCheck용 RestController 추가

- Dockerfile
- pom.xml
WAR 배포에서 JAR 배포로 변경
- pom.xml 변경 (WAR -> JAR)
- Dockerfile 변경
Issue: #119
> chore: WAR -> JAR

- src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
- src/main/java/com/kube/noon/building/repository/BuildingProfileRepository.java
- src/main/java/com/kube/noon/building/service/BuildingProfileService.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
- src/main/java/com/kube/noon/common/security/support/KakaoTokenSupport.java
- src/main/java/com/kube/noon/places/domain/PositionRange.java
- src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
- src/main/java/com/kube/noon/places/service/PlacesService.java
- src/main/java/com/kube/noon/places/service/PlacesServiceImpl.java
- src/test/java/com/kube/noon/building/repository/TestBuildingProfileRepository.java
- src/test/java/com/kube/noon/building/service/TestBuildingService.java
위도, 경도 좌표로 건물 정보 받아오는 코드를 구현했으며 추가적으로 건물 프로필 관련 리팩토링을 했습니다.
- BuildingProfileRepository에 도로명주소로 건물 검색 구현
- BuildingProfileService에 위도, 경도 좌표로 건물 검색 구현
- BuildingProfileRestController에 위도, 경도 좌표로 건물 검색 구현
- PositionRange 리팩토링: 네 꼭짓점 좌표 => 최소/최대 위도, 최소/최대 경도
Issue: #125
> feat: 위도, 경도 좌표로 건물 정보 받아오기 구현

- src/main/java/com/kube/noon/common/zzim/ZzimRepository.java
- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/service/FeedService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
View를 구현하기 위한 로직을 수정했습니다.
- 피드 목록 출력 시 대표 피드, 좋아요, 북마크 여부를 같이 정보를 가져오도록 수정했습니다.
- 검색 관련 기능을 리팩토링하고, 페이징을 추가했습니다.
(내부 로직만 쓰윽 바뀐거라 사진은 따로 없습니다)
#99 에 계속 작성 중입니다.
> refactor : View와 연관된 비즈니스 로직 수정

- src/main/java/com/kube/noon/common/security/filter/TokenRefreshFilter.java
- src/main/java/com/kube/noon/config/WebSecurityConfig.java
- src/main/java/com/kube/noon/member/controller/MemberRestController.java
- src/main/resources/application.properties
Cookie에 도메인을 설정함으로써 클라이언트에서 요청을 해도 쿠키가 저장이 된다
- 쿠키 관련된 코드에 setDomain 설정
Issue: #134
> HOTFIX: Cookie에 도메인 설정

- src/main/java/com/kube/noon/chat/controller/ChatroomRestController.java
- src/main/java/com/kube/noon/chat/domain/ChatEntrance.java
- src/main/java/com/kube/noon/chat/domain/Chatroom.java
- src/main/java/com/kube/noon/chat/dto/ChatroomSearchResponseDto.java
- src/main/java/com/kube/noon/chat/repository/ChatroomRepository.java
- src/main/java/com/kube/noon/chat/service/ChatroomSearchService.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomSearchServiceImpl.java
- src/test/java/com/kube/noon/chat/ChatroomSearchServiceImplTest.java
- src/test/java/com/kube/noon/chat/repository/TestChatroomRepository.java
클라이언트에서 필요한 데이터에 맞춰 데이터 명세 변경
기존에는 다음과 같은 데이터를 반환
- chatroomID
- chatroomMinTemp
- chatroomName
- chatroomCreatorId
- chatroomType
리팩토링 후 다음 데이터를 반환
- chatroomId
- chatroomName
- participantCount
- buildingName
- roadAddr
- chatroomCreatorId
- chatroomType
- chatroomMinTemp
Issue: #131
> refactor: 채팅방 검색 리팩토링

- src/main/java/com/kube/noon/common/zzim/ZzimRepository.java
- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/dto/FeedCommentDto.java
- src/main/java/com/kube/noon/feed/dto/FeedDto.java
- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/repository/mybatis/FeedMyBatisRepository.java
- src/main/java/com/kube/noon/feed/service/FeedService.java
- src/main/java/com/kube/noon/feed/service/FeedStatisticsService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/java/com/kube/noon/feed/service/impl/FeedStatisticsServiceImpl.java
- src/main/java/com/kube/noon/feed/util/CalculatorUtil.java
- src/main/resources/mybatis-mapper/feed/FeedMapper.xml
- src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
- src/test/java/com/kube/noon/feed/service/TestFeedStatisticsServiceImpl.java
피드 상세 보기 구현 중 변경된 사항입니다.
- 인기도 순으로 목록을 가져오는 것에 대하여 구현하였습니다.
- 피드 상세 보기에 대하여 여러가지를 수정했습니다
- 상세보기 시 여러 정보를 가져올 수 있도록 수정했습니다(좋아요 수, 조회수, 인기도 등)
- 피드 상세보기를 할 때 사용하는 `feedDto`를 좀 더 상세히 정의했습니다.
#99
> feat : 피드 상세보기 구현 중 변경 사항

- src/main/java/com/kube/noon/chat/chatTest.http
- src/main/java/com/kube/noon/chat/controller/ChatroomRestController.java
- src/main/java/com/kube/noon/chat/domain/Chatroom.java
- src/main/java/com/kube/noon/chat/dto/ChatroomDto.java
- src/main/java/com/kube/noon/chat/dto/ChatroomSearchResponseDto.java
- src/main/java/com/kube/noon/chat/repository/ChatroomRepository.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomSearchServiceImpl.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomServiceImpl.java
- src/main/java/com/kube/noon/common/ScheduledTasks.java
- src/test/java/com/kube/noon/chat/ChatroomRepositoryTest.java
- src/test/java/com/kube/noon/chat/ChatroomSearchServiceImplTest.java
- src/test/java/com/kube/noon/chat/repository/TestChatroomRepository.java
(pull request 내용의 요약을 1~2줄로 요약해서 작성합니다)
> Z ral dog/#38/chat test with other system

- src/main/java/com/kube/noon/common/messagesender/ApickApiAgentImpl.java
- src/main/java/com/kube/noon/member/binder/mapper/member/MemberSimpleDtoBinder.java
- src/main/java/com/kube/noon/member/binder/mapper/memberRelationship/MemberRelationshipSimpleDtoBinder.java
- src/main/java/com/kube/noon/member/binder/mapper/search/MemberRelationshipSearchCriteriaRequestDtoBinder.java
- src/main/java/com/kube/noon/member/controller/MemberRestController.java
- src/main/java/com/kube/noon/member/dto/RequestDto/MemberRelationshipSearchCriteriaRequestDto.java
- src/main/java/com/kube/noon/member/dto/member/AddMemberDto.java
- src/main/java/com/kube/noon/member/dto/member/MemberSimpleDto.java
- src/main/java/com/kube/noon/member/dto/memberRelationship/MemberRelationshipSimpleDto.java
- src/main/java/com/kube/noon/member/repository/impl/MemberJpaRepositoryQueryImpl.java
- src/main/java/com/kube/noon/member/repository/impl/MemberRelationshipJpaRepositoryQueryImpl.java
- src/main/java/com/kube/noon/member/service/MemberService.java
- src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
- src/main/java/com/kube/noon/member/validator/MemberScanner.java
- src/main/java/com/kube/noon/member/validator/MemberValidator.java
- src/test/java/com/kube/noon/member/repository/TestMemberRepository.java
팔로잉팔로워 관련 로직 리팩토링, 문자 기능 실제 작동으로 변경 발표전 풀리퀘스트
팔로잉팔로워 관련 로직 리팩토링, 문자 기능 실제 작동으로 변경 발표전 풀리퀘스트
> Hyeon jun0527/#136/following follower

- Dockerfile
> test를 위한 prod삭제

- src/main/java/com/kube/noon/building/dto/BuildingSearchResponseDto.java
BuildingSearchResponseDto에서 buildingId가 필요해서 추가했습니다.
- BuildingSearchResponseDto에 buildingId 추가
> refactor: BuildingSearchResponseDto에 누락된 데이터 추가

- src/main/java/com/kube/noon/member/controller/MemberRestController.java
Related To:#136
이제 카카오 로그인 될 끕니다 쿠키 셋도메인했습니다
이제 카카오 로그인 될 끕니다 쿠키 셋도메인했습니다
> Refactor:이제 카카오 로그인 될 끕니다

- src/main/java/com/kube/noon/member/controller/MemberRestController.java
Related To:#136
HotFIx:카카오로그인 오류해결
HotFIx:카카오로그인 오류해결
> HotFIx:카카오로그인 오류해결

- src/main/java/com/kube/noon/member/controller/MemberRestController.java
Related To:#136
카카오로그인에러해결
카카오로그인에러해결
> Refactor: 카카오로그인

- src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
- src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
검색할 때 데이터가 안 맞는 부분이 있어 수정했습니다.
- 검색 관련 에러 수정
Issue: #148
> fix: 검색 관련 에러 제거

- src/main/java/com/kube/noon/common/ObjectStorageAWS3S.java
오브젝트 스토리지 접근제어 추가
클라이언트가 이미지를 Object Storage의 Object를 read 할 수 있도록 수정
> refactor : Object Storage CannedAcl PublicRead

- Dockerfile
로그인 테스트를 위해 스프링 profile에 prod를 추가합니다
Dockerfile 환경변수 설정에서 prod 추가
> chore: Dockerfile Spring profile 변경

- src/main/java/com/kube/noon/config/WebConfig.java
- src/main/java/com/kube/noon/member/controller/MemberRestController.java
쿠키를 브라우저에 전송하기 위한 CORS 설정
- CORS 설정에서 exposed Header 추가
Issue: #154
> chore: CORS 설정에서 exposedHeader 설정

- src/main/java/com/kube/noon/config/WebConfig.java
- src/main/java/com/kube/noon/member/controller/MemberRestController.java
Cookie를 반영하기 위한 설정
Cookie를 반영하기 위해 CORS 설정을 만짐
[https://kindloveit.tistory.com/100](https://kindloveit.tistory.com/100)
> chore: 쿠키 설정

- src/main/java/com/kube/noon/member/controller/MemberRestController.java
브라우저에 저장된 JWT access token으로 현재 로그인 유저 정보를 가져올 수 있습니다.
- 로그인한 상태로 (JWT token을 가지고 있는 상태로) /member/getLoginMember에 접근하면 현재 로그인한 유저 정보를 가져옵니다
Issue: #163
> feat: JWT access token으로 현재 로그인 유저 정보 가져오기

- src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
- src/main/java/com/kube/noon/building/dto/BuildingApplicantDto.java
- src/main/java/com/kube/noon/building/dto/BuildingDto.java
- src/main/java/com/kube/noon/building/repository/BuildingProfileRepository.java
- src/main/java/com/kube/noon/building/service/BuildingProfileService.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
- src/main/java/com/kube/noon/common/zzim/ZzimRepository.java
- src/main/java/com/kube/noon/customersupport/controller/CustomerSupportRestController.java
- src/test/java/com/kube/noon/building/service/TestBuildingService.java
빌딩 프로필 부분을 리팩토링했습니다.
위키 페이지 생성 로직을 추가하고, 
건물 구독과 건물 등록 신청 메서드를 분리하였습니다. (+그에 대한 테스트 코드를 작성하였습니다.)
#159
> refactor : wiki page creation

- src/main/java/com/kube/noon/building/controller/BuildingWikiRestController.java
- src/main/java/com/kube/noon/building/dto/wiki/BuildingWikiEditRequestDto.java
- src/main/java/com/kube/noon/building/dto/wiki/BuildingWikiPageResponseDto.java
- src/main/java/com/kube/noon/building/dto/wiki/BuildingWikiReadPageResponseDto.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
- src/main/java/com/kube/noon/building/service/BuildingWikiService.java
- src/main/java/com/kube/noon/building/service/buildingwiki/BuildingWikiEmptyServiceImpl.java
- src/main/java/com/kube/noon/building/service/buildingwiki/BuildingWikiRestTemplateServiceImpl.java
- src/test/java/com/kube/noon/building/service/TestBuildingWikiRestTemplateServiceImpl.java
- src/test/java/com/kube/noon/building/service/buildingwiki/TestBootBuildingWikiRestTemplateServiceImpl.java
건물 위키와 관련된 API 구현
- 건물 위키 페이지 조회, 편집 페이지 조회, 편집 기능
Issue: #160
> feat: BuildingWikiRestController 구현

- src/main/java/com/kube/noon/building/controller/BuildingWikiRestController.java
- src/test/java/com/kube/noon/building/service/buildingwiki/TestBootBuildingWikiRestTemplateServiceImpl.java
editWiki request parameter 변경
- @ModelAttribute => @RequestBody
Issue: #160
> refactor: 건물 위키 REST API 명세 변경

- src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
- src/main/java/com/kube/noon/places/repository/PlacesSearchApiNaverMapsApiRepository.java
네이버에서 제공하는 지역 검색 API를 사용해 검색
잘 되는 모습
Issue: #167
> refactor: 네이버 지역 검색 API 사용

- src/main/java/com/kube/noon/chat/controller/ChatroomRestController.java
- src/main/java/com/kube/noon/chat/domain/ChatApply.java
- src/main/java/com/kube/noon/chat/dto/ChatEntranceDto.java
- src/main/java/com/kube/noon/chat/repository/ChatEntranceRepository.java
- src/main/java/com/kube/noon/chat/repository/ChatroomRepository.java
- src/main/java/com/kube/noon/chat/service/ChatroomService.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomServiceImpl.java
채팅방에서 회원을 추방하는 로직을 구현했습니다
- chatEntrance 에서 kick column 을 1 로 세팅
- 채팅방 조회시에도 kick column 0 인 chatEntrance만 불러옴
> feat : 채팅방 추방 로직 구현

- Dockerfile
(pull request 내용의 요약을 1~2줄로 요약해서 작성합니다)
> chore: Dockerfile에서 prod 제거

- src/main/java/com/kube/noon/common/messagesender/ApickApiAgent.java
- src/main/java/com/kube/noon/common/messagesender/ApickApiAgentImpl.java
- src/main/java/com/kube/noon/common/security/support/KakaoTokenSupport.java
- src/main/java/com/kube/noon/config/WebConfig.java
- src/main/java/com/kube/noon/member/binder/mapper/member/AddMemberDtoBinder.java
- src/main/java/com/kube/noon/member/binder/mapper/memberRelationship/MemberRelationshipSimpleDtoBinder.java
- src/main/java/com/kube/noon/member/controller/MemberRestController.java
- src/main/java/com/kube/noon/member/dto/member/AddMemberDto.java
- src/main/java/com/kube/noon/member/dto/member/UpdateMemberDto.java
- src/main/java/com/kube/noon/member/dto/memberRelationship/FindMemberRelationshipListByCriteriaDto.java
- src/main/java/com/kube/noon/member/dto/memberRelationship/FindMemberRelationshipListByCriteriaResponseDto.java
- src/main/java/com/kube/noon/member/dto/memberRelationship/MemberRelationshipCountDto.java
- src/main/java/com/kube/noon/member/repository/MemberRelationshipJpaRepository.java
- src/main/java/com/kube/noon/member/repository/MemberRelationshipJpaRepositoryQuery.java
- src/main/java/com/kube/noon/member/repository/MemberRepository.java
- src/main/java/com/kube/noon/member/repository/impl/MemberRelationshipJpaRepositoryQueryImpl.java
- src/main/java/com/kube/noon/member/repository/impl/MemberRepositoryImpl.java
- src/main/java/com/kube/noon/member/service/MemberService.java
- src/main/java/com/kube/noon/member/service/impl/KakaoServiceImpl.java
- src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
- src/main/java/com/kube/noon/member/validator/MemberScanner.java
- src/main/resources/application.properties
- src/test/java/com/kube/noon/member/repository/TestMemberRepository.java
- src/test/java/com/kube/noon/setting/service/TestSettingServiceImpl.java
> Hyeon jun0527/#172/block logic

- src/main/java/com/kube/noon/common/security/filter/TokenRefreshFilter.java
filterChain.doFilter() 메소드가 호출된 이후에 response header에 값을 세팅할 수 없다. 이 시점에서는 이미 클라이언트에 response가 전송된 이후이기 때문이다.
- filterChain.doFilter() 메소드가 호출되기 전에 리프레시 토큰을 재발급
Issue: #176
> fix: 리프레시 토큰 필터 관련 문제 해결

- src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
- src/main/java/com/kube/noon/building/repository/BuildingSummaryRepositoryImpl.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
- src/main/java/com/kube/noon/customersupport/controller/CustomerSupportRestController.java
- src/main/java/com/kube/noon/customersupport/service/CustomerSupportService.java
- src/main/java/com/kube/noon/customersupport/service/CustomerSupportServiceImpl.java
고객지원 컨트롤러에 deleteBlurredFile 추가
빌딩 컨트롤러에 FeedSummary 추가했습니다.
FeedSummary는 스케줄러에 의해 12시마다 호출되는 로직이지만, 
테스트 및 발표를 위해 클라이언트에서 호출이 가능하도록 수정했습니다.
> refactor : deleteBlurredFile , FeedSummary 추가

- src/main/java/com/kube/noon/chat/controller/ChatMatchingRestController.java
- src/main/java/com/kube/noon/chat/domain/Chatroom.java
- src/main/java/com/kube/noon/chat/dto/ChatApplyDto.java
- src/main/java/com/kube/noon/chat/dto/ChatroomDto.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatMatchingServiceImpl.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomServiceImpl.java
1:1 채팅방을 위한 로직수정
- buliding Id, dajung Temp 널러블
> feat : 1:1 채팅방 구현

- src/main/java/com/kube/noon/member/controller/MemberRestController.java
어제 만들었는데 빠졌던 차단관련된 엔드포인트 추가, 구글로그인에 프로필 사진 안옮겨지는 문제 해결
어제 만들었는데 빠졌던 차단관련된 엔드포인트 추가, 구글로그인에 프로필 사진 안옮겨지는 문제 해결
> Hyeon jun0527/#178/view refactoring

- src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
- src/main/java/com/kube/noon/building/dto/BuildingNotFoundResponseDto.java
- src/main/java/com/kube/noon/building/exception/NotRegisteredBuildingException.java
- src/main/java/com/kube/noon/building/service/BuildingProfileService.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
- src/main/java/com/kube/noon/places/controller/PlacesRestController.java
- src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
- src/main/java/com/kube/noon/places/repository/PlacesRepository.java
- src/main/java/com/kube/noon/places/service/PlacesService.java
- src/main/java/com/kube/noon/places/service/PlacesServiceImpl.java
- src/test/java/com/kube/noon/places/service/TestPlacesServiceImpl.java
등록되지 않은 건물 데이터 응답
- 등록되지 않은 건물에 대한 데이터 응답
Issue: #170
> feat: 등록되지 않은 건물 가져오기 데이터 정의

- src/main/java/com/kube/noon/member/controller/MemberRestController.java
- src/main/java/com/kube/noon/member/service/MemberService.java
- src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
- src/main/java/com/kube/noon/member/validator/MemberScanner.java
- src/main/java/com/kube/noon/member/validator/MemberValidator.java
전체적인 리팩토링
로그인 실패시 전달할 메세지 리팩토링
> Refactor: 전체적인 리팩토링

- Dockerfile
- src/main/java/com/kube/noon/config/WebSecurityConfig.java
빌드 설정 변경
- accesscontrol을 profile에 추가
> chore: add profile - accesscontrol

- src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
- src/main/java/com/kube/noon/building/dto/BuildingChartDto.java
- src/main/java/com/kube/noon/building/service/BuildingProfileService.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
- src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepositoryImpl.java
> feat : building chart

- src/main/java/com/kube/noon/member/controller/MemberRestController.java
- src/main/java/com/kube/noon/member/service/MemberService.java
- src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
- src/main/java/com/kube/noon/member/validator/MemberValidator.java
- src/test/java/com/kube/noon/member/service/TestMemberService.java
프로필 사진 관련 로직 수정
프로필 사진 관련 로직 수정.. 이제 사용자가 사진을 잘 넣을 수 있고, 디비에 잘 들어갔다가 나옵니다.
> Refactor:프로필사진관련로직수정

- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/domain/FeedVotes.java
- src/main/java/com/kube/noon/feed/domain/converter/MapToJsonConverter.java
- src/main/java/com/kube/noon/feed/dto/FeedVotesDto.java
- src/main/java/com/kube/noon/feed/service/FeedVotesService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedVotesServiceImpl.java
본래 작성했던 투표 로직을 좀 더 개선해서 제작하였습니다.
- 투표 테이블에 중복 투표를 막기 위한 voterIds를 추가하였습니다. 단, 로직은 아직 안만들어서 조만간 만들 예정입니다.
- 그 외에 보충할 로직을 추가했습니다. 좀 더 정교하게 데이터를 확인하고 작동하도록 했습니다.
없음
> feat : 간단한 투표 로직 완성

- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/dto/FeedMegaphoneDto.java
- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/service/FeedService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/java/com/kube/noon/feed/service/impl/FeedVotesServiceImpl.java
투표 게시판과 관련된 로직을 수정하고, 확성기 피드와 관련된 로직을 구현하였습니다.
RDBS에서 투표 게시판을 누른 회원을 관리하기 위해 로직을 수정하였습니다. 핵심 로직은 다음과 같습니다.
```
// feedVotes 내의 voterIds를 확인하여 votes를 갱신한다.
private List<Integer> updateVotes(Map<String, Integer> voterIds, int optionSize) {
// 1. 새로운 배열을 만듬
List<Integer> votes = new ArrayList<>(Collections.nCopies(optionSize, 0));
// 2. 투표 개수를 계산할 Map을 만듬
Map<Integer, Integer> valueCountMap = new HashMap<>();
for (Integer value : voterIds.values()) {
valueCountMap.put(value, valueCountMap.getOrDefault(value, 0) + 1);
}
// 3. 각 투표 계산 결과를 votes에 반영
Iterator<Integer> iterator = valueCountMap.keySet().iterator();
while (iterator.hasNext()) {
int key = iterator.next();
votes.set(key, valueCountMap.get(key));
}
return votes;
}
```
위 로직을 통해 투표한 회원을 관리함과 동시에 투표 개수를 계산할 수 있습니다. 그리고 중복 투표가 되지 않도록 …
> feat : 투표 관련 로직 수정, 확성기 관련 로직 추가

- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
차트 데이터 제공 기준을 변경했습니다.
화면단에서 데이터를 표현하는 정책이 바뀜에 따라, 제공하는 데이터도 변경하였습니다.
> refactor : 차트 정렬 기준 변경에 따른 코드 수정

- src/main/java/com/kube/noon/member/controller/MemberRestController.java
- src/main/java/com/kube/noon/member/dto/auth/googleLoginRequestDto.java
> HotFix:구글로그인 오류 해결

- src/main/java/com/kube/noon/member/dto/auth/googleLoginRequestDto.java
구글로그인 이슈로 Dto수정
구글로그인 이슈로 Dto수정
> Refactor:구글로그인 이슈로 Dto수정

- src/main/java/com/kube/noon/chat/controller/ChatroomAdminRestController.java
- src/main/java/com/kube/noon/chat/domain/Chatroom.java
- src/main/java/com/kube/noon/chat/exceptions/ChatroomGlobalExceptionHandler.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomServiceImpl.java
- src/main/java/com/kube/noon/config/ChatroomSchedularConfig.java
- 폭파시간 24시간으로 수정 (서버실행시 바로 삭제해버리는데 24시간후 최초 폭파하도록 수정)
- 건물에서 채팅방생성시 채팅방이 제대로 입력안되는 오류 수정
-
> Z ral dog/#38/chat refactoring refactoring refactoring

- src/main/java/com/kube/noon/common/security/authentication/authtoken/GoogleTokenAuthentication.java
- src/main/java/com/kube/noon/common/security/authentication/authtoken/generator/GoogleTokenAuthenticationGenerator.java
- src/main/java/com/kube/noon/common/security/authentication/provider/GoogleTokenAuthenticationProvider.java
- src/main/java/com/kube/noon/common/security/support/GoogleTokenSupport.java
- src/main/java/com/kube/noon/config/WebSecurityConfig.java
- src/main/java/com/kube/noon/member/controller/MemberRestController.java
- src/main/java/com/kube/noon/member/dto/auth/GoogleLoginRequestDto.java
구글 로그인 인증/인가 로직을 Spring Security로 구현
이제 구글 로그인으로 로그인됨
그러나 한 번 로그인하면 로그인할 때 발급받은 토큰이 만료되면 다시 로그인해야 함.
Issue: #199
> feat: 구글 로그인 인증/인가 로직 구현

- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
- src/main/java/com/kube/noon/customersupport/controller/CustomerSupportRestController.java
건물 등록신청 로직 수정
건물 등록신청에서 profile activated와 유저 구독의 activated를 고려하려 로직을 수정했습니다.
> fix : 건물 등록신청 로직 수정

- src/main/java/com/kube/noon/member/controller/MemberRestController.java
- src/main/java/com/kube/noon/member/dto/member/ProfileAccessResultDto.java
- src/main/java/com/kube/noon/member/service/MemberService.java
- src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
환경설정별 프로필공개범위구현
맞팔공개 팔로워공개 전체공개 비공개에 따라 프로필공개범위를 제한한다.
> Refactor:환경설정별 프로필공개범위구현

- src/main/java/com/kube/noon/member/controller/MemberRestController.java
- src/main/java/com/kube/noon/member/repository/impl/MemberRepositoryImpl.java
로그인에러 잡기. 토큰 삭제로직이 로컬에서는 잘 됩니다.
로그인에러 잡기. 토큰 삭제로직이 로컬에서는 잘 됩니다.
> Refactor:로그인에러잡는중

- src/main/java/com/kube/noon/chat/controller/ChatroomRestController.java
- src/main/java/com/kube/noon/chat/domain/ChatEntrance.java
- src/main/java/com/kube/noon/chat/dto/ChatEntranceDto.java
- src/main/java/com/kube/noon/chat/repository/ChatEntranceRepository.java
- src/main/java/com/kube/noon/chat/service/ChatroomService.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomServiceImpl.java
- chatEntrance 를 member 와 Join 시킴
> feat : 채팅 리펙토링

- src/main/java/com/kube/noon/building/repository/BuildingSummaryRepositoryImpl.java
- src/main/java/com/kube/noon/common/zzim/ZzimRepository.java
- src/main/java/com/kube/noon/customersupport/controller/CustomerSupportRestController.java
- src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepository.java
- src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepositoryImpl.java
- src/main/java/com/kube/noon/customersupport/service/CustomerSupportService.java
- src/main/java/com/kube/noon/customersupport/service/CustomerSupportServiceImpl.java
- src/test/java/com/kube/noon/customersupport/service/TestCustomerSupportService.java
사용자가 선택한 블러 수준에 맞게 블러 처리,
피드 요약 데이터가 적절하지 않거나 부족할 경우 예외처리
> refactor : 블러 수준 설정

- src/main/java/com/kube/noon/customersupport/service/CustomerSupportServiceImpl.java
> refactor : List sorting

- src/main/java/com/kube/noon/common/ObjectStorageAPI.java
- src/main/java/com/kube/noon/common/ObjectStorageAPIProfile.java
- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
테스트 중 버그 수정 및 설정 변경입니다.
FeedSummaryDto에 null 처리가 안되어있는 부분을 처리했습니다.
이제 Object storage에 사진이나 영상 등 파일을 넣으면 무조건 공개가 되도록 수정했습니다.
없음
> fix : null 처리 및 Object Storage 설정 변경

- src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepositoryImpl.java
그린아이 API 요청할 때, 이미지/사진 외 처리할 수 없는 파일에 대한 예외 처리를 했습니다.
기존에도 서비스에서 FileType으로 방어를 했었습니다
그럼에도 DB 데이터를 잘못 INSERT하거나, 다른 분의 로직에서 잘못된 입력이 발생한 것을 목격하여 예외 처리를 추가했습니다.
> refactor : greeneye exception

- Dockerfile
profile에 prodddd 추가 (건물 위키 Bean 등록용)
> chore: update Dockfile

- src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
- src/main/java/com/kube/noon/building/dto/LiveliestChatroomBuildingDto.java
- src/main/java/com/kube/noon/building/dto/MemberBuildingSubscriptionResponseDto.java
- src/main/java/com/kube/noon/building/service/BuildingProfileService.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
- src/test/java/com/kube/noon/building/service/TestBuildingService.java
[이 풀 리퀘스트](https://github.com/kuberMAPtes/noon-main-client-server/pull/180)에 필요한 데이터를 추가했습니다.
- 구독 제공자 정보 제공
- 건물별 활발한 채팅방 제공
Issue: #190
> feat: 지도 관련 데이터 추가

- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/dto/FeedEventDto.java
- src/main/java/com/kube/noon/feed/dto/FeedLIkeMemberDto.java
- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
- src/main/java/com/kube/noon/feed/repository/FeedEventRepository.java
- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/repository/mybatis/FeedMyBatisRepository.java
- src/main/java/com/kube/noon/feed/service/FeedService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/resources/mybatis-mapper/feed/FeedMapper.xml
- src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
> feat, fix : 이벤트 피드 구현 및 버그 수정

- src/main/java/com/kube/noon/common/security/support/KakaoTokenSupport.java
카카오 로그인 관련 가끔씩 나는 에러 해결
최현준이란 닉네임이 이미 존재하는 상황에서 카카오 회원가입시
닉네임 중복으로 생기는 에러를 해결
> Refactor:카카오 로그인 에러

- src/main/java/com/kube/noon/customersupport/service/CustomerSupportServiceImpl.java
시간대 서울로 명시
locatDateTime => ZonedDateTime 
#225
> refactor : Specifying Time Zone for Deployment

- src/main/java/com/kube/noon/chat/controller/ChatMatchingRestController.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomServiceImpl.java
채팅 신청 오류해결
1:1 채팅방에선 건물이 null 이므로 예외처리를 해줬음
> feat : 1:1채팅 신청 수락 리펙토링

- src/main/java/com/kube/noon/customersupport/service/ChatbotServiceImpl.java
맨날 못 알아처먹는 멍청한 챗봇인 줄 알았더니 제가 멍청이처럼 다룬 탓이었네요
지능 높은 챗봇을 사용할 수 있게 됐습니다.
> fix: chatbot 안 되는 버그 수정

- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
- src/main/java/com/kube/noon/feed/repository/FeedCommentRepository.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
UI 수정 시 필요한 데이터를 추가했습니다.
- 피드 목록 보기에 댓글 개수, 좋아요 개수, 조회수를 출력하기 위해 코드를 일부 수정했습니다.
(더 적을 게 없넹...)
없음
> fix : 필요한 데이터 추가

- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
피드 목록을 최신순으로 정렬하게 했습니다.
JPA 내용을 살짝 변경해 최신순으로 정렬하도록 했습니다.
없음
> feat : 자신이 작성한 피드, 건물 프로필 피드 최신순으로 정렬

- src/main/java/com/kube/noon/common/validator/Problems.java
- src/main/java/com/kube/noon/setting/service/validator/SettingServiceValidator.java
- src/test/java/com/kube/noon/setting/service/validator/TestSettingServiceValidator.java
메소드가 너무 긴 것들을 좀 줄이면서 책임을 분산시켰습니다.
- SettingServiceValidator 리팩토링했습니다.
- 다른 것들도 다 리팩토링하고 다 뒤집어엎고 싶었으나... 혹시나 되던 게 안 될까 봐 더는 건드리지 않았습니다.
Issue: #234
> refactor: 코드를 리팩토링했습니다.

- src/main/java/com/kube/noon/chat/controller/ChatroomRestController.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomServiceImpl.java
> feat : 1:1채팅 버그해결

- src/main/java/com/kube/noon/feed/domain/Feed.java
- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/java/com/kube/noon/feed/service/recommend/FeedRecommendationMemberId.java
UI 개선 중 필요한 정보나 기능을 추가하고, 최신 순으로 정렬했습니다.
1. 추천 알고리즘에서 관련된 회원의 닉네임을 들고 오도록 수정했습니다.
2. 좋아요, 북마크, 건물 구독 피드가 zzim_id에 맞춰 최근에 한 것 먼저 나오도록 정렬했습니다.
3. 이벤트 시간 설정이 표준시로 저장되던 것을 한국 시간으로 변경했습니다.
없음
> feat : 필요한 기능 추가, 정렬 개선

- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/resources/mybatis-mapper/feed/FeedMapper.xml
테스트 중 발견한 버그를 해결했습니다.
1. MyBatis SQL에 activated 관련 예외 처리를 하여 삭제가 정상적으로 처리되도록 했습니다.
2. 피드 알고리즘 작동 시, 날짜가 최신순으로 정렬되지 않았던 현상을 수정했습니다.
(없음)
> fix : 피드 정렬 및 삭제 관련 버그 수정

- src/main/java/com/kube/noon/config/ChatroomSchedularConfig.java
영상편집을 위해 채팅방 시간 설정 5분
영상편집을 위해 채팅방 시간 설정 5분
> Editing chat5
