- src/main/java/com/kube/noon/notification/converter/NotificationTypeConverter.java
- src/main/java/com/kube/noon/notification/domain/Notification.java
- src/main/java/com/kube/noon/notification/domain/NotificationType.java
- src/main/java/com/kube/noon/notification/dto/NotificationDto.java
- src/main/java/com/kube/noon/notification/repository/NotificationRepository.java
- src/main/java/com/kube/noon/notification/service/NotificationService.java
- src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
- src/main/java/com/kube/noon/places/repository/PlacesRepository.java
- src/main/java/com/kube/noon/places/service/PlacesService.java
- src/test/java/com/kube/noon/notification/repository/TestNotificationRepository.java
- src/test/java/com/kube/noon/places/repository/TestPlacesNaverMapsApiRepositoryImpl.java
알림을 데이터베이스에 저장하는 NotificationRepository 구현
- Notifcation, NotificationType 객체 구현
- JPA 기반 NotificationRepository 구현
- NotifcationRepository 테스트 코드 작성
- places 서브시스템 리팩토링
Issue: #22 
[AttributeConverter 설명](https://velog.io/@ewan/JPA-AttributeConverter-%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%9C-%EC%97%94%ED%8B%B0%ED%8B%B0-%EA%B5%AC%EC%84%B1)
참조 무결성을 위해 members 테이블에 데이터를 추가해야 하는데 MemberRepository가 없는 관계로 기본 JDBC 코드로 members 테이블에 레코드를 넣었습니다.
이때 트랜잭션을 유지하기 위해 DataSourceUtils를 사용했는데 DataSourceUtils에 대해서 학습하면 좋을 것 같습니다. DataSourceUtils는 테스트 코드에만 나타나므로 필수적으로 학습할 필요는 없습니다.
[DataSourceUtils API](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/datasource/DataSourceUtils.html)
[스프링 DB 접근 기술 - 순수 JDBC](https://m.blog.naver.com/adamdoha/222078797274)
> feat: NotificationRepository 구현

- src/main/java/com/kube/noon/common/zzim/Zzim.java
- src/main/java/com/kube/noon/common/zzim/ZzimRepository.java
- src/main/java/com/kube/noon/feed/repository/FeedAttachmentRepository.java
- src/main/java/com/kube/noon/feed/repository/FeedCommentRepository.java
- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/repository/TagFeedRepository.java
- src/main/java/com/kube/noon/feed/repository/TagRepository.java
- src/main/java/com/kube/noon/feed/repository/mybatis/TagMyBatisRepository.java
- src/main/resources/mybatis-mapper/feed/TagMapper.xml
- src/test/java/com/kube/noon/feed/repository/TestFeedAttachmentRepository.java
- src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
- src/test/java/com/kube/noon/feed/repository/TestTagFeedRepository.java
피드와 관련된 쿼리 관련 코드를 추가했습니다.
- JPA 코드 추가 및 테스트를 추가하였습니다.
- 진행하는 과정에서 zzim Entity, repository가 조금 변경되었습니다. 하단의 [issue](https://github.com/kuberMAPtes/noon-main-api-server/issues/32)에 작성했으니 참고 부탁드립니다. 
- 현재 반영된 코드 내에 일부 쓸모없는 (또는 사용하지 않는) 코드가 있을겁니다. (사용하지 않는 lib import 등) 이는 다음 PR 때 수정하여 반영하겠습니다.
- 사용한 DB 초기화 코드는 [SQL docs Repository](https://github.com/kuberMAPtes/noon-sql-docs/blob/main/Winterhana/test_db_init_private.sql)에 올려두었으니 참고 부탁드립니다. DB 관리자님이 배포하신 것과 조금 다릅니다. 앞으로 사용한 SQL이 있으면 Repository 내의 `Winterhana` 폴더에 반영할 예정입니다.
issue : #32
> feat : Winterhana/#32/feed sql : 피드와 관련된 JPA 코드 추가 및 테스트 완료

- src/main/java/com/kube/noon/feed/domain/Feed.java
- src/main/java/com/kube/noon/feed/domain/FeedAttachment.java
- src/main/java/com/kube/noon/feed/dto/FeedAttachmentDto.java
- src/main/java/com/kube/noon/feed/dto/FeedDto.java
- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
- src/main/java/com/kube/noon/feed/repository/FeedAttachmentRepository.java
- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/repository/TagRepository.java
- src/main/java/com/kube/noon/feed/repository/mybatis/TagMyBatisRepository.java
- src/main/java/com/kube/noon/feed/service/FeedService.java
- src/main/java/com/kube/noon/feed/service/FeedSubService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
- src/test/java/com/kube/noon/feed/repository/TestFeedAttachmentRepository.java
- src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
- src/test/java/com/kube/noon/feed/repository/TestTagFeedRepository.java
- src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
- src/test/java/com/kube/noon/feed/service/TestFeedSubServiceImpl.java
FeedService 를 구현하고 FeedSubService를 구현 중입니다.
- `FeedService` : 피드의 목록을 가져오거나 피드 자체의 CRUD를 모아둔 Service입니다.
- `FeedSubService` : 피드 외 연관이 있는 테이블에 대한 CRUD를 모아둔 Service입니다.
- Service 기능에 따른 리스트는 issue : #37 에서 확인 가능합니다.
- 요구사항에 따라 FeedSubService에 우선적으로 구현할 것을 구현하고 PR를 보냅니다. 추후에 완성하고 PR를 다시 보낼 예정입니다.
issue : #37
> feat : Winterhana/#37/feed service : FeedService 추가, FeedSubService 추가 중

- src/main/java/com/kube/noon/building/repository/BuildingSummaryRepository.java
- src/main/java/com/kube/noon/building/repository/BuildingSummaryRepositoryImpl.java
- src/main/java/com/kube/noon/building/service/BuildingProfileService.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
- src/test/java/com/kube/noon/building/service/TestBuildingService.java
- src/test/java/com/kube/noon/customersupport/repository/TestCustomerSupportRepository.java
빌딩 피드를 Naver CLOVA Summary로 요약하는 기능을 구현했습니다.
특정 시간마다 AI요약 서비스를 호출하여 건물별 피드 요약 정보를 Update하는 로직이 추가되었습니다.
스프링 스케줄러를 사용하였습니다. 
스케줄링에 관한 메서드와 필드 묶음인 ScheduledTasks 클래스를 common패키지에 만들었습니다.
성진님의 채팅방 폭발(?) 기능도 이곳에서 작성하시면 될 것 같습니다.
API의 key와 요약을 위한 buildingId들을 정의한 메타데이터는 드라이브에 올려두었습니다.
buildingId를 메타데이터화 한 이유는 @Scheduled된 메서드에 파라미터를 줄 수 없기 때문입니다.
#52
> feat : 빌딩 피드 AI 요약 구현

- src/main/java/com/kube/noon/common/validator/IllegalServiceCallException.java
- src/main/java/com/kube/noon/common/validator/Problems.java
- src/main/java/com/kube/noon/common/validator/ValidationAspect.java
- src/main/java/com/kube/noon/common/validator/Validator.java
- src/test/java/com/kube/noon/notification/service/TestNotificationServiceImpl.java
```ValidationAspect```에서 발생하는 ```NullPointerException```을 해결했다.
- ```AopProxyUtils.ultimateTargetClass()``` 메소드를 사용해 오리지널 클래스를 가져와 거기에 있는 ```@Validator``` 정보를 가져옴
Issue: #64
> hotfix: ValidationAspect에서 발생하는 NullPointerException 해결

- src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepository.java
- src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepositoryImpl.java
- src/main/java/com/kube/noon/customersupport/service/CustomerSupportService.java
- src/main/java/com/kube/noon/customersupport/service/CustomerSupportServiceImpl.java
- src/test/java/com/kube/noon/customersupport/service/TestCustomerSupportService.java
#58 의 유해사진 필터링 전에 NCloud Green Eye를 이용해 1차 필터링하는 기능을 구현했습니다.
임의로 5개의 첨부파일을 두고, file_url을 Object Storage의 url로 Insert하여 테스트했습니다.
#58 
[CLOVA GreenEye API 가이드](https://api.ncloud-docs.com/docs/ai-application-service-greeneye)
> feat : Green Eye 유해사진 필터링 구현 feat

- src/main/java/com/kube/noon/customersupport/service/ChatbotService.java
- src/main/java/com/kube/noon/customersupport/service/ChatbotServiceImpl.java
- src/test/java/com/kube/noon/customersupport/service/TestChatbotServiceImpl.java
챗봇을 구현했습니다.
- 학습된 Chatbot으로 API 요청
#76
[Naver 공식 문서](https://guide.ncloud-docs.com/docs/chatbot-chatbot-overview)
[야, 너두 할 수 있어! 문과생의 톡톡 챗봇 제작기
](https://blog.naver.com/PostView.naver?blogId=n_cloudplatform&logNo=221901199311&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fwww.google.com%2F&trackingCode=external&directAccess=false)
ㄴ얘가 하라는 대로 하니까 다 됨
> feat: Chatbot 구현

- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/domain/Feed.java
- src/main/java/com/kube/noon/feed/dto/FeedDto.java
- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
- src/main/java/com/kube/noon/feed/dto/TagFeedDto.java
- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/service/FeedService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
- src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
- src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
발견된 버그들을 해결 및 완화하였습니다.
1. 피드 상세보기를 가져올 시 (feed/detail/{feedId}), tagText 내에서 순환 참조 문제가 일어나는 현상 해결
tagFeedDto에서 순환 참조를 하고 있는 것으로 파악하여 이를 수정하였습니다.
```
public class TagFeedDto {
private int tagFeedId;
// private Feed feed;
// private Tag tag;
private int feedId;
private int tagId;
...
}
```
2. addFeed 중 addNotice일 때 building이 굳이 필요 없는데 요구했던 현상 완화
연관관계를 아예 바꾸면 코드를 다시 다 고쳐야 해서 피드를 추가/수정 시 예외사항을 일단 뒀습니다.
```
public int addFeed(FeedDto feedDto) {
Feed addFeed = FeedDto.toEntity(feedDto);
if(addFeed.getFeedCategory() == FeedCategory.NOTICE) {
addFeed.setBuilding(null);
}
addFeed.setActivated(true);
...
public int updateFeed(FeedDto feedDto) {
Feed updateFeed = feedRepository.findByFeedId(feedDto.getFeedId());
if(updateFeed.getFeedCategory() == FeedCategory.NOTICE) {
updateFeed.setBuilding(null); …
```
> fix : FeedService 관련 버그 해결

- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/dto/AddTagDto.java
- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/repository/TagRepository.java
- src/main/java/com/kube/noon/feed/service/FeedService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
- src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
FeedController를 보완하는 과정을 거쳤습니다.
- FeedController의 테스트를 `Postman`을 통해 진행하였습니다. 시간이 허락했다면 테스트 코드도 따로 짜고 싶었는데 거기까진 시간이 안될 거 같아서 임의로 테스트를 진행했습니다. 당연히 찾지 못한 버그가 있을 수 있으니 계속 주시하겠습니다.
- Controller를 구성할 때 Get Method 사용 시 쿼리스트링을, Post Method 사용 시 URI을 사용하여 데이터를 가져오게 했습니다. 혹시 표준에 맞지 않다면 바로 수정하겠습니다.
- 피드 목록을 가져올 때 `Pageable`을 통한 일부분만 가져오는 기능을 적용했습니다.
- `Swagger`(이 프로젝트에서는 `Springdoc` 사용)를 통해서 Controller를 간단하게 명세화했습니다. 사용할 때 참고하시면 좋을 거 같습니다. 
#71 
이 PR 이후로 Client 쪽으로 넘어가서 작업하겠습니다.
> feat, docs : FeedController 테스트 완료, 목록 페이징 작업, Swagger 명세화

- pom.xml
배포 환경 에러를 막기 위한 dependency 삭제
이거 없어도 잘 돌아가서 일단 PR 보냅니다.
NULL
> chore : matout-integreation dependency 삭제

- src/main/java/com/kube/noon/chat/controller/ChatroomAdminRestController.java
- src/main/java/com/kube/noon/chat/repository/ChatroomRepository.java
- src/main/java/com/kube/noon/chat/service/ChatroomSearchService.java
- src/main/java/com/kube/noon/chat/service/ChatroomService.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomSearchServiceImpl.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomServiceImpl.java
- src/test/java/com/kube/noon/chat/ChatroomSearchServiceImplTest.java
(pull request 내용의 요약을 1~2줄로 요약해서 작성합니다)
- chat/service/ChatroomSearchService 에 건물별 채팅방 목록 조회, 건물별 채팅방목록 검색 등의 메소드 추가하였습니다
- chat/controller/ChatroomAdminRestController 에 관리자 기능 (전체 채팅방 검색 및 삭제) 추가 하였습니다
- repository, impl 테스트 시작
cf. 리뷰반영 사항
도엽 - bulider 패턴 아직x
경도 - Sl4J, javadoc 넣는중
> feat : chatroomSearchService 및 adminRestController 추가 (24.6.12)

- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/dto/FeedDto.java
- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
- src/main/java/com/kube/noon/feed/dto/UpdateFeedDto.java
- src/main/java/com/kube/noon/feed/repository/TagFeedRepository.java
- src/main/java/com/kube/noon/feed/service/FeedService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
Clinet View를 제작하면서 Server 로직 중 필요한 수정을 정리했습니다.
- 데이터가 일부 누락됐던 버그(또는 놓친 점)을 수정했습니다
- FeedList에 `작성 날짜`, `건물 이름`
- 태그와 관련하여 개선점이 있었습니다.
- 피드 상세보기를 가져올 때 하나의 서비스 내에서 바로 태그 내용을 가지고 올 수 있도록 하였습니다.
- 피드 추가, 수정 시 태그까지 한 번에 저장할 수 있도록 로직을 수정했습니다.
- `updateFeedDto`를 추가하여 필요한 정보만 수정할 수 있도록 수정했습니다.
#99 
위 이슈는 삭제하지 않고 수정 사항이 생길 때마다 계속 수정할 예정입니다.
> refactor : 피드 내부 로직 관련 수정 사항

- src/main/java/com/kube/noon/common/security/filter/TokenRefreshFilter.java
- src/main/java/com/kube/noon/common/security/support/KakaoTokenSupport.java
KakaoTokenSupport에서 구현되지 않은 부분을 구현합니다.
- Refresh token으로 토큰 재발급
- 토큰에서 회원 ID 추출
- 토큰 만료 체크
- 토큰이 Refresh Token인지 체크
- Refresh Token 만료는 구현하지 않음 (코드 주석 참고)
> feat: KakaoTokenSupport 나머지 구현

- src/main/java/com/kube/noon/config/WebSecurityConfig.java
Spring Security 접근 권한 문제 해결
- Request Matcher에 접근 권한이 필요한 endpoint 외에 모두 허용
Issue: #117
> hotfix: Spring Security 접근 권한 문제

- src/main/java/com/kube/noon/member/validator/MemberValidationRule.java
UpdateMemberDto에서 nickname이 null일 경우 검증하지 않도록 변경
- Nickname이 null이라는 것은 nickname을 변경하지 않겠다는 것을 의미한다. 그러므로 nullable이다.
Issue: #121
> fix: UpdateMemberDto에서 Nickname이 null일 때 검증하지 않음

- src/main/java/com/kube/noon/feed/dto/FeedPopularityDto.java
- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/resources/mybatis-mapper/feed/FeedMapper.xml
- src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
피드 목록을 가져오는 과정에서 변경된 사항들입니다.
- 추천 알고리즘 실행 시, 일부 피드가 중복되어 나타나는 현상을 수정했습니다.
- 건물별  인기 피드 목록을 가져올 때, 상위 5개만 가져오도록 하고 건물ID 대신 유저 닉네임을 가져오도록 수정했습니다.
- `setFeedSummaryDtoLikeAndBookmark` 에서 null exception이 나는 현상을 해결했습니다.
#99 에서 계속 추가 및 수정중입니다.
> fix : 피드 목록에 대한 내부 로직 수정

- src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
- src/main/java/com/kube/noon/building/dto/BuildingNotFoundResponseDto.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
해당 좌표에 건물이 없을 때/해당 좌표에 건물은 있으나 등록된 건물이 아닐 때
각각 경우에 해당하는 응답이 있어야 함
Issue: #154
> refactor: 좌표를 파라미터로 건물 프로필 받아올 때 응답 케이스 추가

- src/main/java/com/kube/noon/common/ObjectStorageAPI.java
- src/main/java/com/kube/noon/feed/dto/FeedAttachmentDto.java
- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
- src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
사진과 동영상을 가져오는 과정에서 데이터를 수정하였습니다.
- 첨부파일을 가져오기 위해 로직을 크게 변경하였는데, 이 과정은 다음과 같습니다.
1. 데이터가 없을 때 null 처리 -> 클라이언트 쪽에서 이를 처리합니다.
2. 파일 확장자를 기반으로 MIME 타입을 반환 -> 이 파일이 사진인지 동영상인지 파악합니다.
3. 대략적으로 attachmentId를 통해 첨부파일을 하나씩 가져오는 방식이라고 생각하시면 됩니다. 즉, 한 번에 가져오는 등의 개선의 여지가 있으나 일단 구현부터 하는게 좋을 거 같아 이 방향으로 구현하였습니다. 
없음
> refactor : 사진 / 동영상 사진을 가져오기 위한 데이터 수정

- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/domain/FeedVotes.java
- src/main/java/com/kube/noon/feed/domain/converter/ListToIntegerConverter.java
- src/main/java/com/kube/noon/feed/domain/converter/ListToStringConverter.java
- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
- src/main/java/com/kube/noon/feed/dto/FeedVotesDto.java
- src/main/java/com/kube/noon/feed/repository/FeedVotesRepository.java
- src/main/java/com/kube/noon/feed/service/FeedVotesService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedVotesServiceImpl.java
투표 게시판을 만들기 위한 기본 내용을 작성했습니다. 필요에 따라 더 구현할 수 있습니다.
기본적인 투표 로직에 대하여 작성하였습니다.  
물론 빠진 부분이 있기 때문에 (예시 : 멤버별로 한 번씩 투표하게 하기) 현재 더 추가할 여지가 많습니다.
구현 과정에서 작은 table이 추가되었는데, 이는 다음과 같습니다.
```
CREATE TABLE feed_votes (
feed_id INT PRIMARY KEY,
question VARCHAR(255) NOT NULL,
options JSON NOT NULL,
votes JSON NOT NULL,
FOREIGN KEY (feed_id) REFERENCES feed(feed_id)
);
```
후에 구현이 완료되면 클라우드 DB에 테이블만 하나 추가하면 될 거 같습니다.
없음
> feat : 투표 게시판 구현을 위한 로직 추가

- src/main/java/com/kube/noon/common/zzim/ZzimRepository.java
- src/main/java/com/kube/noon/feed/dto/FeedVotesDto.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
- src/main/java/com/kube/noon/feed/service/impl/FeedVotesServiceImpl.java
- src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
- src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
Client 관련 작업 중 발생한 버그나 요구사항을 처리했습니다.
첨부파일(FeedAttachment), 댓글(FeedComment)에 대한 비활성화도 같이 진행하도록 수정하였습니다.
비동기적으로 이뤄지는 작업 중 좋아요 신청 요청이 2번씩 들어가면 이와 관련된 버그가 발생하였습니다. 이를 좀 더 방어할 수 있도록 List 관련 로직으로 처리하였습니다.  
"완화" 라는 표현을 사용한 이유는 완벽한 해결책은 아니기 때문입니다. 다른 경우의 버그가 발생하면 다시 수정할 예정입니다.
투표 화면을 만드는 중 null을 전달하는게 필요해져서 Exception 대신 null을 전달하도록 수정했습니다. null 관련 로직은 Client에서 처리합니다.
없음
> fix : 투표 관련 작업 중 요구사항 변경 및 기타 버그 해결

- src/main/java/com/kube/noon/common/ObjectStorageAPIProfile.java
- src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
프로필 사진을 저장하기 위한 버킷을 따로 생성하고 연동했습니다.
- Object Storage의 프로필 사진용 버킷을 따로 생성하고 이를 연동하는 API code를 복사하여 분리하였습니다.
- Hard-coding된 부분은 바로 실사용을 하기 위해 조치한 것이며, 이에 따른 key 분리가 필요합니다.
없음
> feat : 프로필 사진 버킷 생성 및 분리

- pom.xml
- src/main/java/com/kube/noon/chat/controller/ChatMatchingRestController.java
- src/main/java/com/kube/noon/chat/controller/ChatroomAdminRestController.java
- src/main/java/com/kube/noon/chat/controller/ChatroomRestController.java
- src/main/java/com/kube/noon/chat/domain/ChatEntrance.java
- src/main/java/com/kube/noon/chat/domain/Chatroom.java
- src/main/java/com/kube/noon/chat/dto/ChatroomDto.java
- src/main/java/com/kube/noon/chat/exceptions/ChatroomAutoDeleteFailException.java
- src/main/java/com/kube/noon/chat/exceptions/ChatroomGlobalExceptionHandler.java
- src/main/java/com/kube/noon/chat/exceptions/ChatroomNotFoundException.java
- src/main/java/com/kube/noon/chat/repository/ChatEntranceRepository.java
- src/main/java/com/kube/noon/chat/repository/ChatroomRepository.java
- src/main/java/com/kube/noon/chat/service/ChatroomService.java
- src/main/java/com/kube/noon/chat/service/DeleteChatroomsJob.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomSearchServiceImpl.java
- src/main/java/com/kube/noon/chat/serviceImpl/ChatroomServiceImpl.java
- src/main/java/com/kube/noon/common/security/AccessDefinition.java
- src/main/java/com/kube/noon/config/ChatroomSchedularConfig.java
채팅방 자동삭제에 대한 로직을 만듦
1) 채팅방 폭파 관련 로직
- 서버에서 채팅방 자동삭제 (activated 를 0으로 만듦)
- 다음 자동삭제까지 남은 시간(트리거 예정시간 - 현재 서버시간)을 클라이언트에 리턴
- 채팅방 조회시 activated 가 1인것만 조회하도록 함
2) 내 채팅목록 조회할 때 chatEntrances 의 수도 조회하여 채팅방마다 입장한 사람도 볼 수 있도록함
3) 코드 리뷰 받은 예외 처리 부분(500 -> 40x), 채팅타입 (String -> chatroomType) 변경
> feat : 채팅방 폭파 +@

- src/main/java/com/kube/noon/building/repository/BuildingProfileRepository.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
도로명 주소로 조회하는 기능을 activated에 따라 구분했습니다
건물 등록 신청에서는 profileActivated가 false인 데이터가 필요하고,
지도 쪽에서는 true인 데이터가 필요하기 때문입니다.
> fix : 도로명주소 조회 기능별 구분

- src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
건물명이 도로명 주소가 되던 시절이 있었으나 이젠 아니다
이젠 건물명으로 데이터가 전송된다. 그러나 개중에 건물명이 없는 건물이 있다. (아마 원래 있는데 네이버 Geocode API에서 제공 안 해 주는 듯하다) 그래서 이걸 어떻게 해야 할지 생각해 봐야 한다.
Issue: #195
> fix: 건물명으로 건물명 대신 도로명주소가 뜨던 거 수정

- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/domain/FeedEvent.java
- src/main/java/com/kube/noon/feed/dto/FeedCommentDto.java
- src/main/java/com/kube/noon/feed/dto/FeedDto.java
- src/main/java/com/kube/noon/feed/dto/FeedEventDto.java
- src/main/java/com/kube/noon/feed/dto/FeedVotesDto.java
- src/main/java/com/kube/noon/feed/dto/UpdateFeedDto.java
- src/main/java/com/kube/noon/feed/repository/FeedEventRepository.java
- src/main/java/com/kube/noon/feed/service/FeedSubService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
- src/main/java/com/kube/noon/feed/service/impl/FeedVotesServiceImpl.java
- src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
- src/test/java/com/kube/noon/feed/service/TestFeedSubServiceImpl.java
댓글 관련한 로직을 조금 수정했습니다.  
그리고 이벤트 피드를 구현하기 위해 간단한 테이블을 추가했고, 이에 대한 로직을 작성 중입니다.
댓글 작성 시 닉네임을 가져오기 위해 로직을 수정했습니다.
```
CREATE TABLE feed_event (
feed_id INT PRIMARY KEY,
event_date DATETIME NOT NULL,
FOREIGN KEY (feed_id) REFERENCES feed(feed_id)
);
```
이벤트 지정 날짜를 저장하는 테이블을 하나 추가했습니다.
위 테이블을 사용한 로직을 추가했습니다. 일반 피드 관련 기능에 추가하였으며, 요구사항에 따라 계속 추가할 예정입니다. 
없음
> feat : 댓글 관련 수정 사항 추가, 이벤트 피드에 대한 테이블 추가 및 이에 대한 로직 추가

- src/main/java/com/kube/noon/common/zzim/Zzim.java
- src/main/java/com/kube/noon/feed/controller/FeedRestController.java
- src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
- src/main/java/com/kube/noon/feed/service/FeedService.java
- src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
- src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
좋아요, 북마크, 목록 보기에 대한 로직을 재구성했습니다.
대표적으로 2가지가 변경되었습니다.
컬럼에 관련 내용이 없으면 Exception이 나는 것을 대비하기 위해 따로 로직을 구성했습니다.
목록을 가져올 대상의 memberId와 로그인을 한 memberId를 구분하여 로직을 재구성했습니다.
없음
> fix : 좋아요, 북마크, 목록 보기에 대한 로직 재구성

- src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
- src/test/java/com/kube/noon/member/service/TestMemberService.java
회원 관계에 따른 접근제한에 관련된 메서드 에러 해결
회원 관계에 따른 접근제한에 관련된 메서드에서 null처리를 안해서 memberRelaitionshipDto가 null이면 생기는 에러를 해결함
> Hyeon jun0527/#178/view refactoring

- src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
- src/main/java/com/kube/noon/building/dto/SubscriberDto.java
- src/main/java/com/kube/noon/building/service/BuildingProfileService.java
- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
- src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
건물 프로필에서 구독자 목록을 가져올 때 공개 범위를 체크합니다.
현재 로그인한 회원(Viewer)이 조회 가능한 구독자(Member) 목록만을 표시합니다. 
따라서 파라미터에 viewerId가 추가되었습니다.
viewerId가 memberId와 같다면 무조건 조회할 수 있도록 했습니다.
Viewer와 Member의 맞팔 관계를 체크할 때 MemberServiceImpl내의 메서드(서비스가 아닌)를 써야하기 때문에 접근 제한자를 수정했습니다. 추후 구조 자체를 리팩토링 할 수 있을 것 같습니다.
또한 findMemberRelationship에서 null발생 가능성이 있으므로  getSubscribers에서 일단은 명시적으로 null체크를 했습니다. 
추후에 Member쪽에서 Optional사용 등으로 리팩토링 할 수 있을 것 같습니다.
#228
> refactor : Check Subscriber List PublicRange

- src/main/java/com/kube/noon/notification/service/NotificationServiceImpl.java
알림 수신 대상의 알림 수신 설정이 "수신하지 않음"일 경우 알림을 보내지 않음
- NotificationServiceImpl에 알림 수신 대상의 알림 수신 여부 체크
- 알림 수신 대상이 존재하지 않을 회원일 경우 알림을 보내지 않음
Issue: #231
> feat: 알림 수신 여부 확인

- src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
서비스 이용자가 거의 없는 상태에서 채팅방 활발함을 보여주기 위해 기준을 상당히 내렸습니다.
채팅방 활발함 기준 인하
1단계: 10개 미만
2단계: 10~20개
3단계: 20~30개
4단계: 30~40개
5단계: 40개 이상
> chore: 채팅방 활발함 기준 인하

- src/main/java/com/kube/noon/feed/repository/FeedRepository.java
- src/main/resources/mybatis-mapper/feed/FeedMapper.xml
테스트 중 발견한 버그를 수정합니다.
1. 인기 태그는 제대로 정렬이 되지 않아 역순으로 확인하는 버그 수정
2. 건물 구독은 최신 피드가 뜨도록 수정
없음
> fix : 인기 태그와 건물 구독 별 피드 목록 정렬 수정
